name: "Waypoints"
main: com.github.sessional.waypoints.WpsPlugin
version: "1.0"
commands:
  wps:
    description: root command
    usage: /<command> [subcommand] [args]
  waypoints:
    description: root command
    usage: /<command> [subcommand] [args]